### ISSUE TITLE
Displaying Q06012_en

### ISSUE THREAD

**Issue by adilbhatia98** [Understanding-Economics/Understanding-Economics.github.io#169]
The choices are very different for the different treatments, so what is the best way to display this

**Comment by Rainett** [comment]
which survey are you talking about? estate? 
(btw, new health data uploaded, variables ltcare_1 to ltcare_8, order follows the one of "survey questionnaire")
![ltcare](https://user-images.githubusercontent.com/55542591/80543589-34531980-897d-11ea-8767-a2b8470c58fe.jpeg)

**Comment by adilbhatia98** [comment]
sorry - estate survey!
i believe any bold id's in the spreadsheet are not displayed

**Comment by Rainett** [comment]
Hum not sure, maybe display the full question before the graph then separate the two answers possibilities in "statement 1" and "statement 2" for the legend?

**Comment by adilbhatia98** [comment]
What do you mean by statement 1 and statement 2? Do you mean a pair of statements for each randomization treatment?

Adil Bhatia

**Comment by Rainett** [comment]
If I understand well, the problem is that answers are randomized, not questions. People have to choose between two statements, the first is in favor of passing wealth and the second is in favor of taxing wealth. If we want a common legend for all the graphs, we could display the question with the statements (even if it is long) right before the graph, and then the choices would be statement 1 and statement 2. Does that makes sense?
